### ISSUE TITLE
Support Rails 6 multiple database config?

### ISSUE THREAD

**Issue by takamario** [winebarrel/ridgepole#289]
Is there any plan to support Rails 6 multiple database config?

Rails 6 has support multiple database config and config file structure of yaml becomes one level deeper like this.
```yaml
production:
  primary:
    database: my_primary_database
    user: root
    adapter: mysql
  primary_replica:
    database: my_primary_database
    user: root_readonly
    adapter: mysql
    replica: true
  animals:
    database: my_animals_database
    user: animals_root
    adapter: mysql
    migrations_paths: db/animals_migrate
  animals_replica:
    database: my_animals_database
    user: animals_readonly
    adapter: mysql
    replica: true
```
Needs specifying database name when Rails native migartion like this.
```bash
$ rails db:migrate:animals
```
or
```bash
$ rails g migration CreateDogs name:string --database animals
```

I've created a workaround PR. 
https://github.com/takamario/ridgepole/pull/1/files

Any ideas? Thanks.
