### ISSUE TITLE
According to the sample example given in the homepage, it is found that the foreign key cannot be created successfully

### ISSUE THREAD

**Issue by dhc-yuchenglin** [winebarrel/ridgepole#351]
1、ridgepole_test project directory
```
.
├── Gemfile
├── Gemfile.lock
├── Schemafile
├── database.yml
└── vendor
    └── bundle
```

2、Gemfile settings
```
# frozen_string_literal: true

source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '2.6.3'

#gem 'ridgepole', '~> 0.7.0'
gem 'ridgepole', '~> 0.9.0'
#gem 'mysql2', '>= 0.3.18', '< 0.5'
gem 'mysql2', '~>0.5'
gem 'dotenv', '~> 2.7', '>= 2.7.2'
```

3、database.yml setting content
```
default: &default
  adapter: mysql2
  encoding: utf8mb4
  charset: utf8mb4
  collation: utf8mb4_general_ci
  pool: <%= ENV.fetch("MAX_THREADS") { 5 } %>
  host: <%= ENV.fetch("DB_HOST") { '127.0.0.1' } %>
  username: <%= ENV.fetch("DB_USER") { 'root' } %>
  password: <%= ENV.fetch("DB_PASSWORD") { '' } %>

development:
  <<: *default
  database: <%= ENV.fetch("DB_NAME") { 'test' } %>
```

4、version specified by .ruby-version
```2.6.3```

5、.env environment variable setting
```
MAX_THREADS=5
DB_HOST=127.0.0.1
DB_USER=root
DB_PASSWORD=
DB_NAME=test
```

6、vender installation command
```$ bundle install --path vendor/bundle```

7、System information
```
OS:macOS Big Sur11.2.2
mysql: Server version: 5.7.10 MySQL Community Server (GPL)
bundle: Bundler version 2.0.2
```

8、Schemafile content(https://github.com/winebarrel/ridgepole#foreign-key   reference address)
```
# encoding: utf-8

create_table "parent", force: :cascade do |t|
end

create_table "child", id: false, force: :cascade do |t|
  t.integer "id"
  t.integer "parent_id"
end

add_index "child", ["parent_id"], name: "par_ind", using: :btree

add_foreign_key "child", "parent", name: "child_ibfk_1"
```

9、ridgepole execute table creation Schemafile
```$ bundle exec dotenv -f ".env" bundle exec ridgepole -c database.yml -E development --apply -f Schemafile```
error infomation
```
Apply `Schemafile`
-- create_table("parent")
   -> 0.0439s
-- create_table("child", {:id=>false})
   -> 0.0295s
-- add_index("child", ["parent_id"], {:name=>"par_ind", :using=>:btree})
   -> 0.0467s
-- add_foreign_key("child", "parent", {:name=>"child_ibfk_1"})
[ERROR] Column `parent_id` on table `child` does not match column `id` on `parent`, which has type `bigint(20)`. To resolve this issue, change the type of the `parent_id` column on `child` to be :bigint. (For example `t.bigint :parent_id`).
Original message: Mysql2::Error: Cannot add foreign key constraint
   5:   t.column("id", :"integer", **{:limit=>4})
   6:   t.column("parent_id", :"integer", **{:limit=>4})
   7: end
   8: add_index("child", ["parent_id"], **{:name=>"par_ind", :using=>:btree})
   9: 
* 10: add_foreign_key("child", "parent", **{:name=>"child_ibfk_1"})
        /Users/${user}/Documentsworkspace/Schema/ridgepole_test/vendor/bundle/ruby/2.6.0/gems/mysql2-0.5.3/lib/mysql2/client.rb:131:in `_query'
```

Question:
1. Is there a problem with the official example?
2. The local version of ridgepole is the latest version 0.9.1. Do you want to add primary_key when creating a foreign key to prevent the above problems? Is there an introduction in the official document?
3. The problems mentioned above still exist when ridgepole is reduced to 0.7.4 and mysql2 is reduced to 0.4.10. Therefore, which version of ridgepole is the referenced official example based on? Is the current official example still valuable?
@winebarrel
