### ISSUE TITLE
ridgepole 0.5.0 fails to command [ridgepole -c database.yml --apply -f Schemafile]

### ISSUE THREAD

**Issue by Y-Fujikawa** [winebarrel/ridgepole#38]
Trying to apply to the database, but an error occurred.

```shell
$ ridgepole -c database.yml --apply -f Schemafile
$ [ERROR] undefined method `has_key?' for "database.yml":String
```

### Version
Ruby : 2.2.0
Rails : 4.2.0
OS : OS X

### database.yml
```yaml
default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password: 
  socket: /tmp/mysql.sock

development:
  <<: *default
  database: test_ridgepole
```

### Schemafile
```
create_table "comments", force: true do |t|
  t.string   "comment"
  t.datetime "created_at"
  t.datetime "updated_at"
end
```
